// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCLryF-OqYr1l_Ta7FnAHG2muyOp7FijU',
    appId: '1:882373173227:android:e2f8c4786defe058fb03ae',
    messagingSenderId: '882373173227',
    projectId: 'flutter-login-app-82dc9',
    storageBucket: 'flutter-login-app-82dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc9QwF15WXzAEXwW6PSix2g3M0dmMuFWQ',
    appId: '1:882373173227:ios:106e574b5b0b5e45fb03ae',
    messagingSenderId: '882373173227',
    projectId: 'flutter-login-app-82dc9',
    storageBucket: 'flutter-login-app-82dc9.appspot.com',
    androidClientId: '882373173227-5ri4njdvgsg3f6utag3ln5bhgh0av8eo.apps.googleusercontent.com',
    iosClientId: '882373173227-cbbg2ocobpul8of55oofv43kgm6jckrn.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginfirebase',
  );
}
